Remove-Alias -Name 'ac' -Force
Remove-Alias -Name 'cat' -Force
Remove-Alias -Name 'chdir' -Force
Remove-Alias -Name 'clc' -Force
Remove-Alias -Name 'clear' -Force
Remove-Alias -Name 'clhy' -Force
Remove-Alias -Name 'cli' -Force
Remove-Alias -Name 'clp' -Force
Remove-Alias -Name 'cls' -Force
Remove-Alias -Name 'clv' -Force
Remove-Alias -Name 'cnsn' -Force
Remove-Alias -Name 'compare' -Force
Remove-Alias -Name 'cpi' -Force
Remove-Alias -Name 'cpp' -Force
Remove-Alias -Name 'cvpa' -Force
Remove-Alias -Name 'dbp' -Force
Remove-Alias -Name 'diff' -Force
Remove-Alias -Name 'dnsn' -Force
Remove-Alias -Name 'ebp' -Force
Remove-Alias -Name 'epal' -Force
Remove-Alias -Name 'epcsv' -Force
Remove-Alias -Name 'erase' -Force
Remove-Alias -Name 'etsn' -Force
Remove-Alias -Name 'exsn' -Force
Remove-Alias -Name 'fc' -Force
Remove-Alias -Name 'fhx' -Force
Remove-Alias -Name 'fl' -Force
Remove-Alias -Name 'ft' -Force
Remove-Alias -Name 'fw' -Force
Remove-Alias -Name 'gal' -Force
Remove-Alias -Name 'gbp' -Force
Remove-Alias -Name 'gc' -Force
Remove-Alias -Name 'gci' -Force
Remove-Alias -Name 'gcm' -Force
Remove-Alias -Name 'gcs' -Force
Remove-Alias -Name 'gdr' -Force
Remove-Alias -Name 'gerr' -Force
Remove-Alias -Name 'ghy' -Force
Remove-Alias -Name 'gi' -Force
Remove-Alias -Name 'gjb' -Force
Remove-Alias -Name 'gl' -Force
Remove-Alias -Name 'gm' -Force
Remove-Alias -Name 'gmo' -Force
Remove-Alias -Name 'gp' -Force
Remove-Alias -Name 'gps' -Force
Remove-Alias -Name 'gpv' -Force
Remove-Alias -Name 'group' -Force
Remove-Alias -Name 'gsn' -Force
Remove-Alias -Name 'gsv' -Force
Remove-Alias -Name 'gu' -Force
Remove-Alias -Name 'gv' -Force
Remove-Alias -Name 'h' -Force
Remove-Alias -Name 'history' -Force
Remove-Alias -Name 'icm' -Force
Remove-Alias -Name 'iex' -Force
Remove-Alias -Name 'ihy' -Force
Remove-Alias -Name 'ii' -Force
Remove-Alias -Name 'ipal' -Force
Remove-Alias -Name 'ipcsv' -Force
Remove-Alias -Name 'ipmo' -Force
Remove-Alias -Name 'irm' -Force
Remove-Alias -Name 'iwr' -Force
Remove-Alias -Name 'kill' -Force
Remove-Alias -Name 'ls' -Force
Remove-Alias -Name 'man' -Force
Remove-Alias -Name 'measure' -Force
Remove-Alias -Name 'mi' -Force
Remove-Alias -Name 'mount' -Force
Remove-Alias -Name 'mp' -Force
Remove-Alias -Name 'mv' -Force
Remove-Alias -Name 'nal' -Force
Remove-Alias -Name 'ndr' -Force
Remove-Alias -Name 'ni' -Force
Remove-Alias -Name 'nmo' -Force
Remove-Alias -Name 'nsn' -Force
Remove-Alias -Name 'nv' -Force
Remove-Alias -Name 'ogv' -Force
Remove-Alias -Name 'oh' -Force
Remove-Alias -Name 'ps' -Force
Remove-Alias -Name 'pwd' -Force
Remove-Alias -Name 'r' -Force
Remove-Alias -Name 'rbp' -Force
Remove-Alias -Name 'rcjb' -Force
Remove-Alias -Name 'rcsn' -Force
Remove-Alias -Name 'rd' -Force
Remove-Alias -Name 'rdr' -Force
Remove-Alias -Name 'ren' -Force
Remove-Alias -Name 'ri' -Force
Remove-Alias -Name 'rjb' -Force
Remove-Alias -Name 'rm' -Force
Remove-Alias -Name 'rmdir' -Force
Remove-Alias -Name 'rmo' -Force
Remove-Alias -Name 'rni' -Force
Remove-Alias -Name 'rnp' -Force
Remove-Alias -Name 'rp' -Force
Remove-Alias -Name 'rsn' -Force
Remove-Alias -Name 'rv' -Force
Remove-Alias -Name 'rvpa' -Force
Remove-Alias -Name 'sajb' -Force
Remove-Alias -Name 'sal' -Force
Remove-Alias -Name 'saps' -Force
Remove-Alias -Name 'sasv' -Force
Remove-Alias -Name 'sbp' -Force
Remove-Alias -Name 'set' -Force
Remove-Alias -Name 'shcm' -Force
Remove-Alias -Name 'si' -Force
Remove-Alias -Name 'sl' -Force
Remove-Alias -Name 'sleep' -Force
Remove-Alias -Name 'sls' -Force
Remove-Alias -Name 'sort' -Force
Remove-Alias -Name 'sp' -Force
Remove-Alias -Name 'spjb' -Force
Remove-Alias -Name 'spps' -Force
Remove-Alias -Name 'spsv' -Force
Remove-Alias -Name 'start' -Force
Remove-Alias -Name 'sv' -Force
Remove-Alias -Name 'tee' -Force
Remove-Alias -Name 'type' -Force
Remove-Alias -Name 'wjb' -Force
Remove-Alias -Name 'write' -Force

Remove-Alias -Name 'gcb' -Force
Remove-Alias -Name 'gin' -Force
Remove-Alias -Name 'gtz' -Force
Remove-Alias -Name 'scb' -Force
Remove-Alias -Name 'stz' -Force

Remove-Alias -Name 'cd' -Force
Remove-Alias -Name 'copy' -Force
Remove-Alias -Name 'cp' -Force
Remove-Alias -Name 'del' -Force
Remove-Alias -Name 'dir' -Force
Remove-Alias -Name 'echo' -Force
Remove-Alias -Name 'foreach' -Force
Remove-Alias -Name 'md' -Force
Remove-Alias -Name 'move' -Force
Remove-Alias -Name 'popd' -Force
Remove-Alias -Name 'pushd' -Force
Remove-Alias -Name 'select' -Force
Remove-Alias -Name 'where' -Force
